[package]
name = "pong-midgar"
version = "0.1.0"
authors = ["Gabriel Martinez <reitaka@gmail.com>"]

[dependencies]
cgmath = "0.15"
midgar = { git = "https://github.com/mystal/midgar-engine", branch = "text_rendering" }
noise = "0.4"
rand = "0.3"
